spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_vendor?useSSL=false
    username: postgres
    password: mysecretpassword

  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #JPA Settings
  jpa.hibernate.ddl_auto: update

  security.user:
      name: shivam
      password: password

